Attempt build where proxy and hub share container

diff --git a/start_hub b/start_hub
--- a/start_hub
+++ b/start_hub
@@ -4,24 +4,25 @@
 # terminal interface a little prettier:
 export PS1='\[\033[01;34m\]\w\[\033[00m\]\$'
 
-echo "Archiving proxy server files for proxy build blob..."
-export PROXY_BLOB='proxy_server/proxy_server_app.tar.gz'
-tar -czf $PROXY_BLOB proxy_server/*
-echo "Blob created"
+#echo "Archiving proxy server files for proxy build blob..."
+#export PROXY_BLOB='proxy_server/proxy_server_app.tar.gz'
+#tar -czf $PROXY_BLOB proxy_server/*
+#echo "Blob created"
 
-echo "Creating app for proxy server..."
-python3 create_proxy.py
-echo "Proxy server app created"
+#echo "Creating app for proxy server..."
+#python3 create_proxy.py
+#echo "Proxy server app created"
 
-echo "Connecting to database"
-python3 connect_db.py
-if [ $? -ne 0 ]; then
-    echo "PROXY_PORT value not found."
-else 
-    read PROXY_PORT < proxy_port.txt
-    export PROXY_PORT=$(cat proxy_port.txt)
-    echo "PROXY_PORT = $PROXY_PORT"
-fi
+#echo "Connecting to database"
+#python3 connect_db.py
+#if [ $? -ne 0 ]; then
+#    echo "PROXY_PORT value not found."
+#else 
+#    read PROXY_PORT < proxy_port.txt
+#    export PROXY_PORT=$(cat proxy_port.txt)
+#    echo "PROXY_PORT = $PROXY_PORT"
+#fi
 
 echo "Starting Jupyterhub..."
-exec jupyterhub --ConfigurableHTTPProxy.api_url="${PROXY_WEB_URL}:${PROXY_PORT}"
+exec juptyerhub
+#exec jupyterhub --ConfigurableHTTPProxy.api_url="${PROXY_WEB_URL}:${PROXY_PORT}"
